apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-system-monitoring
spec:
  replicas: 1 # Set the desired number of replicas
  selector:
    matchLabels:
      app: python-system-monitoring
  template:
    metadata:
      labels:
        app: python-system-monitoring
    spec:
      containers:
        - name: dotnet-app
          image: duchoang26/python-system-monitoring:latest # Replace with your Docker image name
          ports:
            - containerPort: 5000 # Expose the port specified in your Dockerfile

---
apiVersion: v1
kind: Service
metadata:
  name: python-system
spec:
  selector:
    app: python-system-monitoring
  ports:
    - protocol: TCP
      port: 80 # Service port
      targetPort: 5000 # Port in the container
  type: NodePort # Use NodePort service type            
